### ISSUE TITLE
Add support for multiple asset dirs

### ISSUE THREAD

**Issue by karpy47** [mbrowniebytes/yii2-clean-assets#1]
I'm using Yii2 adv template with multiple asset dirs. Could you adjust to support multiple asset-dirs?

**Comment by mbrowniebytes** [comment]
added as part of #2 #3 

added tags, so in composer.json, pull from 0.1,0 instead of dev-master


- prior 0.0.1 exposes cleanAssetDir() and options have a dash ie `-verbose` for earlier yii 2.0.?
- new  0.1.0 Issue #1 exposes cleanAssetDirs(), cleanAssetDir($dir) now requires a param, and options are now without a dash ie `verbose` for yii 2.0.13
